FROM node:18.20.2-slim
ENV TZ="Asia/Bangkok"
WORKDIR /app
COPY client/package.json client/package-lock.json ./
RUN npm install
COPY . .
RUN (cd client && npm install)
EXPOSE 4000
CMD ["npm", "run", "dev"]